# Generated by Django 5.2.4 on 2025-09-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_g', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='sale_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
